#include "ClockGetTime.h"
// automatically generated by addhandler.py

std::vector<argument_type> ClockGetTime::getArgumentTypes() {
    return std::vector<argument_type>({AT_INT, AT_STRUCT_TIMESPEC});
}