# ifndef MSC_GETEGID_HANDLER_H
# define MSC_GETEGID_HANDLER_H
// automatically generated by addhandler.py

#include "HandlerRegistry.h"

#define TYPE SYS_getegid

class GetEGid: public Handler {
public:
    GetEGid() {
        _type = TYPE;
    }

    std::vector<argument_type> getArgumentTypes();

    static Handler* create() {
        return new GetEGid();
    };
};

REGISTER_HANDLER(GetEGid, (int) TYPE, GetEGid::create);

#endif