# ifndef MSC_GETGID_HANDLER_H
# define MSC_GETGID_HANDLER_H
// automatically generated by addhandler.py

#include "HandlerRegistry.h"

#define TYPE SYS_getgid

class GetGid: public Handler {
public:
    GetGid() {
        _type = TYPE;
    }

    std::vector<argument_type> getArgumentTypes();

    static Handler* create() {
        return new GetGid();
    };
};

REGISTER_HANDLER(GetGid, (int) TYPE, GetGid::create);

#endif