#include "GetRandom.h"
// automatically generated by addhandler.py

std::vector<argument_type> GetRandom::getArgumentTypes() {
    return std::vector<argument_type>({AT_VOID_PTR_FOLLOW, AT_INT, AT_INT});
}
