# ifndef MSC_GETRANDOM_HANDLER_H
# define MSC_GETRANDOM_HANDLER_H
// automatically generated by addhandler.py

#include "HandlerRegistry.h"

#define TYPE SYS_getrandom

class GetRandom: public Handler {
public:
    GetRandom() {
        _type = TYPE;
    }

    std::vector<argument_type> getArgumentTypes();

    static Handler* create() {
        return new GetRandom();
    };
};

REGISTER_HANDLER(GetRandom, (int) TYPE, GetRandom::create);

#endif