# ifndef MSC_GETTIMEOFDAY_HANDLER_H
# define MSC_GETTIMEOFDAY_HANDLER_H
// automatically generated by addhandler.py

#include "HandlerRegistry.h"

#define TYPE SYS_gettimeofday

class GetTimeOfDay: public Handler {
public:
    GetTimeOfDay() {
        _type = TYPE;
    }

    std::vector<argument_type> getArgumentTypes();

    static Handler* create() {
        return new GetTimeOfDay();
    };
};

REGISTER_HANDLER(GetTimeOfDay, (int) TYPE, GetTimeOfDay::create);

#endif