# ifndef MSC_MKDIR_HANDLER_H
# define MSC_MKDIR_HANDLER_H
// automatically generated by addhandler.py

#include "HandlerRegistry.h"

#define TYPE SYS_mkdir

class Mkdir: public Handler {
public:
    Mkdir() {
        _type = TYPE;
    }

    std::vector<argument_type> getArgumentTypes();

    static Handler* create() {
        return new Mkdir();
    };
};

REGISTER_HANDLER(Mkdir, (int) TYPE, Mkdir::create);

#endif