#include "PrLimit64.h"
// automatically generated by addhandler.py

std::vector<argument_type> PrLimit64::getArgumentTypes() {
    return std::vector<argument_type>({AT_PID_T, AT_INT, AT_STRUCT_RLIMIT64, AT_STRUCT_RLIMIT64});
}