# ifndef MSC_RMDIR_HANDLER_H
# define MSC_RMDIR_HANDLER_H
// automatically generated by addhandler.py

#include "HandlerRegistry.h"

#define TYPE SYS_rmdir

class Rmdir: public Handler {
public:
    Rmdir() {
        _type = TYPE;
    }

    std::vector<argument_type> getArgumentTypes();

    static Handler* create() {
        return new Rmdir();
    };
};

REGISTER_HANDLER(Rmdir, (int) TYPE, Rmdir::create);

#endif