#include "SetRobustList.h"
// automatically generated by addhandler.py

std::vector<argument_type> SetRobustList::getArgumentTypes() {
    return std::vector<argument_type>({AT_STRUCT_ROBUST_LIST_HEAD, AT_SIZE_T});
}