# ifndef MSC_SETROBUSTLIST_HANDLER_H
# define MSC_SETROBUSTLIST_HANDLER_H
// automatically generated by addhandler.py

#include "HandlerRegistry.h"

#define TYPE SYS_set_robust_list

class SetRobustList: public Handler {
public:
    SetRobustList() {
        _type = TYPE;
    }

    std::vector<argument_type> getArgumentTypes();

    static Handler* create() {
        return new SetRobustList();
    };
};

REGISTER_HANDLER(SetRobustList, (int) TYPE, SetRobustList::create);

#endif