# ifndef MSC_STATFS_HANDLER_H
# define MSC_STATFS_HANDLER_H
// automatically generated by addhandler.py

#include "HandlerRegistry.h"

#define TYPE SYS_statfs

class StatFs: public Handler {
public:
    StatFs() {
        _type = TYPE;
    }

    std::vector<argument_type> getArgumentTypes();

    static Handler* create() {
        return new StatFs();
    };
};

REGISTER_HANDLER(StatFs, (int) TYPE, StatFs::create);

#endif