# ifndef MSC_TIME_HANDLER_H
# define MSC_TIME_HANDLER_H
// automatically generated by addhandler.py

#include "HandlerRegistry.h"

#define TYPE SYS_time

class Time: public Handler {
public:
    Time() {
        _type = TYPE;
    }

    std::vector<argument_type> getArgumentTypes();

    static Handler* create() {
        return new Time();
    };
};

REGISTER_HANDLER(Time, (int) TYPE, Time::create);

#endif