#include "Wait4.h"
// automatically generated by addhandler.py

std::vector<argument_type> Wait4::getArgumentTypes() {
    return std::vector<argument_type>({AT_PID_T, AT_UINT64_PTR, AT_INT, AT_STRUCT_RUSAGE});
}