# ifndef MSC_WAIT4_HANDLER_H
# define MSC_WAIT4_HANDLER_H
// automatically generated by addhandler.py

#include "HandlerRegistry.h"

#define TYPE SYS_wait4

class Wait4: public Handler {
public:
    Wait4() {
        _type = TYPE;
    }

    std::vector<argument_type> getArgumentTypes();

    static Handler* create() {
        return new Wait4();
    };
};

REGISTER_HANDLER(Wait4, (int) TYPE, Wait4::create);

#endif