# ifndef MSC_STRUCTRUSAGEPRINTER_PRINTER_H
# define MSC_STRUCTRUSAGEPRINTER_PRINTER_H

// automatically generated by addPrinter.python3

#include "PrinterRegistry.h"
#include "../Utils.h"

#include <sys/resource.h> // struct rusage

class StructRusagePrinter: public Printer {

public:
    void print(argument_value value);

    int getStructLength(argument_type type);

    static Printer* create() {
        return new StructRusagePrinter();
    };

};

REGISTER_PRINTER(StructRusagePrinter, AT_STRUCT_RUSAGE, StructRusagePrinter::create);

#endif