# ifndef MSC_StructRobustListHeadPrinter_PRINTER_H
# define MSC_StructRobustListHeadPrinter_PRINTER_H

// automatically generated by addPrinter.py

#include "PrinterRegistry.h"
#include <linux/futex.h>

class StructRobustListHeadPrinter: public Printer {

public:
    void print(argument_value value);

    int getStructLength(argument_type type);

    static Printer* create() {
        return new StructRobustListHeadPrinter();
    };

};

REGISTER_PRINTER(StructRobustListHeadPrinter, AT_STRUCT_ROBUST_LIST_HEAD, StructRobustListHeadPrinter::create);

#endif