# ifndef MSC_STRUCTSTATFSPRINTER_PRINTER_H
# define MSC_STRUCTSTATFSPRINTER_PRINTER_H

// automatically generated by addPrinter.py

#include "PrinterRegistry.h"
#include <sys/vfs.h> // struct statfs

class StructStatFsPrinter: public Printer {

public:
    void print(argument_value value);

    int getStructLength(argument_type type);

    static Printer* create() {
        return new StructStatFsPrinter();
    };

};

REGISTER_PRINTER(StructStatFsPrinter, AT_STRUCT_STATFS, StructStatFsPrinter::create);

#endif